### ISSUE TITLE
Títulos

### ISSUE THREAD

**Issue by josemariapafo** [Ctrusan/Historia_Woz#1]
Debería poner un título en cada página de tu proyecto en forma de resumen.

**Comment by Ctrusan** [comment]
Muchas gracias por tomarse su tiempo en responder. Esa será una medida que llevaré a cabo para mejorar el proyecto.

Un saludo.

**Comment by Ctrusan** [comment]
Ya está solucionado y lo puedes comprobar. ¡Gracias de nuevo por tu ayuda!
